# Theory Question

Q1. What are data structures, and why are they important?
Ans. Data Structure is the way of organizing and storing data so that it can be accessed and manipulated effeciently. They are important beacuse of-:
1. Code Efficiency.
2. Problem Solving.
3. Real world application.

Some of the Data Structure are as follows-:
1. String
2. List
3. Tuple
4. Set
5. Dictionary

In [2]:
"""
Q2.  Explain the difference between mutable and immutable data types with examples?
Ans. Mutable-:
        1. It can be chnaged after creation.
        2. Usually memory address stays the same after change.
        3. For example-> List, Dict.
     Immutable-:
         1. It can not be changed after creation.
         2. A new object is created if modified.
         3. For example-> String, Tuple.
"""
#Example
a=[1,2,3]
print(a)
a[0]=10
print("Mutuable example",a)

#====================================================
b="Hello"
print(b)
b[0]="Y"
print("Immutable Example",b)

[1, 2, 3]
Mutuable example [10, 2, 3]
Hello

TypeError: 'str' object does not support item assignment

Q3.  What are the main differences between lists and tuples in Python3
Answer->   The key difference between tuples and lists is that while tuples are immutable objects, lists are mutable. This means tuples cannot be changed while lists can be modified. Tuples are also more memory efficient than the lists.

Q4. Describe how dictionaries store data
Answer. Dictionaries are unordered collections of data and are represented with curly brackets { }.Data is stored in a key:value format.
For example- 
dict={'Name':'Ayush','Occup':'Engineer'}

Q5. Why might you use a set instead of a list in Python?
Answer. Since sets automatically eliminate duplicate elements, they are particularly useful for efficiently removing duplicates from lists or tuples. They also make it easy to perform mathematical operations like unions and intersections.


Q6.What is a string in Python, and how is it different from a list?
Answer. A string is a sequence of characters enclosed in single or double quotes. In contrast, a list is a sequence of items, where each item can be of any data type—such as an integer, float, string, or even another list.


Q7.  How do tuples ensure data integrity in Python3
Answer. Tuples in Python are immutable, meaning once they are created, they cannot be changed. This characteristic can be leveraged for data integrity.

Q8. What is a hash table, and how does it relate to dictionaries in Python?
Answer. Hash tables or has maps in Python are implemented through the built-in dictionary data type. The keys of a dictionary in Python are generated by a hashing function. The elements of a dictionary are not ordered and they can be changed.

Q9.  Can lists contain different data types in Python?
Answer. Yes list can contain different data types in Python as it is heterogenous.


Q10. Explain why strings are immutable in Python?
Answer. Python strings are "immutable" which means they cannot be changed after they are created. Since strings can't be changed, we construct *new* strings as we go to represent computed values.

Q11. What advantages do dictionaries offer over lists for certain tasks?
Answer.  Dictionaries in Python offer fast data retrieval: Unlike lists where you have to traverse through each element to find a value, dictionaries use hash tables for quick access to values based on keys.


Q12. Describe a scenario where using a tuple would be preferable over a list?
Answer. Tuples are immutable. Hence, they are primarily used to store data that doesn't change frequently.

Scenario-:
Building an app that handles geographic locations (latitude, longitude). These coordinates should never change once they are assigned because they represent a fixed point.

For this, a tuple would be a better choice than a list.

Q13.How do sets handle duplicate values in Python?
Answer. Sets automatically remove duplicates. When you try to add a duplicate element to a set, it will ignore it and keep only the unique elements. This makes sets ideal for operations where you need to ensure that a collection contains only distinct elements.

Q14. How does the “in” keyword work differently for lists and dictionaries?
Answer. For Lists: The in keyword checks if an element exists in the list by comparing each element in sequence. It checks all elements one by one.
For Dictionaries: The in keyword checks if a key exists in the dictionary, not the value. It checks the keys, not the associated values.

Q15. Can you modify the elements of a tuple? Explain why or why not.
Answer. No, you cannot modify the elements of a tuple after it’s created because tuples are immutable.

Q16.  What is a nested dictionary, and give an example of its use case?
Answer. A nested dictionary is a dictionary where the value is another dictionary. This allows you to represent hierarchical data structures.

Use case: Nested dictionaries are often used to store complex data such as user profiles, configurations, or JSON-like structures.

For Example 
user_info = {
    'name': 'Ayush',
    'address': {'city': 'Delhi', 'zipcode': '110001'},
    'contact': {'phone': '1234567890', 'email': 'ayushsaxenamiet@gmail.com'}
}

print(user_info['address']['city'])  # Output: Delhi


Q17.  Describe the time complexity of accessing elements in a dictionary.
Answer. Accessing elements in a dictionary is very efficient, with an average time complexity of O(1) (constant time). This is because dictionaries in Python are implemented using hash tables, which allow for direct access to values using keys.

Q18. In what situations are lists preferred over dictionaries?
Answers. Lists are preferred when:

The order of elements matters.

You are working with sequences where the index is important.

You don’t need to map keys to values — just store values in a particular order.

Q19. Why are dictionaries considered unordered, and how does that affect data retrieval?
Answer. Dictionaries are considered unordered because, before Python 3.7, they didn’t guarantee the order of key-value pairs.

This means you can’t rely on the order in which items are stored in a dictionary when accessing them.

However, from Python 3.7 onwards, dictionaries maintain the order of insertion, but they are still optimized for fast key lookup, not for maintaining order.

Q20. Explain the difference between a list and a dictionary in terms of data retrieval.
Answers List: You retrieve data from a list using its index (position). Example: my_list[0] retrieves the first item.

Dictionary: You retrieve data from a dictionary using its key. Example: my_dict['key'] retrieves the value associated with 'key'.

# Practical Question

### Q1. Write a code to create a string with your name and print it.

In [4]:
name="Ayush Saxena"
print(name)

Ayush Saxena

### Q2.  Write a code to find the length of the string "Hello World".

In [9]:
# Method 1
str1="Hello World"
print("Length of String is", len(str1))


#Method
str2="Hello World"
count=0
for i in str2:
    for j in i:
        count=count+1
print("Length of string by second method:",count)

Length of String is 11
Length of string by second method: 11

### Q3. Write a code to slice the first 3 characters from the string "Python Programming".

In [11]:
a="Python Programming"
print("First 3 characters from the string are:",a[0:3])

First 3 characters from the string are: Pyt

### Q4. Write a code to convert the string "hello" to uppercase

In [12]:
string="hello"
print(string.upper())

HELLO

### Q5.  Write a code to replace the word "apple" with "orange" in the string "I like apple".

In [14]:
sentence="I like apple"
updated_sentance=sentence.replace('apple','orange')
print(updated_sentance)

I like orange

### Q6. Write a code to create a list with numbers 1 to 5 and print it.

In [15]:
list1=[1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]

### Q7  Write a code to append the number 10 to the list [1, 2, 3, 4].

In [16]:
list2=[1,2,3,4]
list2.append(10)
print(list2)

[1, 2, 3, 4, 10]

### Q8  Write a code to remove the number 3 from the list [1, 2, 3, 4, 5].

In [17]:
list3=[1,2,3,4,5]
list3.remove(3)

In [18]:
print(list3)

[1, 2, 4, 5]

### Q9   Write a code to access the second element in the list ['a', 'b', 'c', 'd']

In [19]:
list4=['a','b','c','d']
print(list4[1])

b

### Q10.  Write a code to reverse the list [10, 20, 30, 40, 50]

In [30]:
#Method 1
list5=[10,20,30,40,50]
print(list5[::-1])


#Method 2
list6=[10,20,30,40,50]
list6.sort(reverse=True)
print(list6)

#Method 3
list7=[10,20,30,40,50]
list8=[]
for i in list7[::-1]:
    list8.append(i)
print(list8)

[50, 40, 30, 20, 10]
[50, 40, 30, 20, 10]
[50, 40, 30, 20, 10]

 ### Q11. Write a code to create a tuple with the elements 100, 200, 300 and print it

In [31]:
a=(100,200,300)
print(a)
print(type(a))

(100, 200, 300)
<class 'tuple'>

# Q12.  Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').

In [1]:
colors=('red', 'green', 'blue', 'yellow')
print(colors[1:])

('green', 'blue', 'yellow')

# Q13.  Write a code to find the minimum number in the tuple (10, 20, 5, 15).

In [3]:
a=(10,20,5,15)
print(min(a))

5

# Q14.  Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

In [4]:
animals= ('dog', 'cat', 'rabbit')
index_cat= animals.index('cat')
print(index_cat)

1

# Q15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.

In [6]:
fruits=('Apple','Pineapple','Kiwi')
'Kiwi' in fruits

True

# Q16.  Write a code to create a set with the elements 'a', 'b', 'c' and print it.

In [7]:
set1={'a','b','c'}
print(set1)

{'a', 'c', 'b'}

# Q17.  Write a code to clear all elements from the set {1, 2, 3, 4, 5}

In [12]:
set2={1,2,3,4,5}
print(set2)
print(set2.clear(),set2)

{1, 2, 3, 4, 5}
None set()

# Q18.  Write a code to remove the element 4 from the set {1, 2, 3, 4}.

In [13]:
set2={1,2,3,4}
set2.remove(4)
print(set2)

{1, 2, 3}

# Q19.  Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.

In [16]:
s1={1,2,3}
s2={3,4,5}
 #Method 1
    
union_set=s1.union(s2)
print(union_set)

{1, 2, 3, 4, 5}

In [17]:
#Method2
s1={1,2,3}
s2={3,4,5}
union_set= s1|s2
print(union_set)

{1, 2, 3, 4, 5}

# Q20.  Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}

In [18]:
#method1
s3={1,2,3}
s4={2,3,4}
intersection_set=s3.intersection(s4)
print(intersection_set)

{2, 3}

In [19]:
#method 2
s3={1,2,3}
s4={2,3,4}
intersection_set_=s3 & s4
print(intersection_set_)

{2, 3}

# Q21.  Write a code to create a dictionary with the keys "name", "age", and "city", and print it.

In [20]:
person = {
    "name": "Alice",
    "age": 30,
    "city": "New York"
}

print("Dictionary:", person)

Dictionary: {'name': 'Alice', 'age': 30, 'city': 'New York'}

# Q22.  Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.

In [21]:
person = {'name': 'John', 'age': 25}
person['country'] = 'USA'
print("Updated dictionary:", person)

Updated dictionary: {'name': 'John', 'age': 25, 'country': 'USA'}

# Q23.  Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.

In [22]:
person = {'name': 'Alice', 'age': 30}
name_value = person['name']
print("Value associated with 'name':", name_value)

Value associated with 'name': Alice

In [24]:
#method 2
name_value = person.get('name')
print("Value associated with 'name':", name_value)

Value associated with 'name': Alice

# Q24.  Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.

In [25]:
# method1 
person = {'name': 'Bob', 'age': 22, 'city': 'New York'}
del person['age']
print("Updated dictionary:", person)

Updated dictionary: {'name': 'Bob', 'city': 'New York'}

In [26]:
#method 2
person = {'name': 'Bob', 'age': 22, 'city': 'New York'}
person.pop('age', None) 
print("Updated dictionary:", person)

Updated dictionary: {'name': 'Bob', 'city': 'New York'}

# Q25.  Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.

In [27]:
person = {'name': 'Alice', 'city': 'Paris'}
if 'city' in person:
    print("The key 'city' exists in the dictionary.")
else:
    print("The key 'city' does not exist in the dictionary.")

The key 'city' exists in the dictionary.

# Q26.  Write a code to create a list, a tuple, and a dictionary, and print them all.

In [28]:
# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a tuple
my_tuple = ('apple', 'banana', 'cherry')

# Creating a dictionary
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

# Printing the list, tuple, and dictionary
print("List:", my_list)
print("Tuple:", my_tuple)
print("Dictionary:", my_dict)

List: [1, 2, 3, 4, 5]
Tuple: ('apple', 'banana', 'cherry')
Dictionary: {'name': 'John', 'age': 30, 'city': 'New York'}

 # Q27.  Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.(replaced)

In [29]:
import random
random_numbers = [random.randint(1, 100) for _ in range(5)]
random_numbers.sort()

print("Sorted list of random numbers:", random_numbers)

Sorted list of random numbers: [5, 25, 86, 91, 92]

# Q28.  Write a code to create a list with strings and print the element at the third index.

In [30]:
string_list = ['apple', 'banana', 'cherry', 'date', 'elderberry']
print("Element at index 3:", string_list[3])

Element at index 3: date

# Q29. Write a code to combine two dictionaries into one and print the result.

In [31]:
dict1 = {'name': 'Alice', 'age': 25}
dict2 = {'city': 'New York', 'job': 'Engineer'}
dict1.update(dict2)
print("Combined dictionary:", dict1)

Combined dictionary: {'name': 'Alice', 'age': 25, 'city': 'New York', 'job': 'Engineer'}

# Q30.  Write a code to convert a list of strings into a set.

In [32]:
string_list = ['apple', 'banana', 'cherry', 'apple', 'banana']
string_set = set(string_list)
print("Converted set:", string_set)

Converted set: {'cherry', 'apple', 'banana'}